#create the follwing services:
# 1. rabbitmq
# 2. zipkin
# 3. mysql
# 4. mongo
# 5. configservice
# 6. eurekaservice
# 7. apigateway
# 8. userservice
# 9. gymservice
# 10. enquiryservice
# 11. ticketservice
# 12. frontend
#
#hint: use depends_on field to ensure proper sequence of container start-ups
#Run `docker-compose up --build` to start all the containers
#Check that all the service features are working as expected using health checks
#Run `docker-compose down` to stop all the containers


version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    container_name: rabbitmqcontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    container_name: zipkincontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb

  mongo:
    image: mongo:latest
    container_name: mongocontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s

  configservice:
    build: ./ConfigService
    image: config-service:1.0-local
    restart: always
    ports:
      - 8888:8888
    container_name: configservicecontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - zipkin

  eurekaservice:
    build: ./EurekaService
    image: eureka-service:1.0-local
    restart: always
    ports:
      - 8761:8761
    container_name: eurekaservicecontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - zipkin
      - configservice

  apigateway:
    build: ./ApiGatewayService
    image: api-gateway:1.0-local
    restart: always
    ports:
      - 9000:9000
    container_name: apigatewaycontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - zipkin
      - configservice
      - eurekaservice

  userservice:
    build: ./UserService
    image: user-service:1.0-local
    restart: always
    ports:
      - 8090:8090
    container_name: userservicecontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - mysql
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  gymservice:
    build: ./GymService
    image: gym-service:1.0-local
    restart: always
    ports:
      - 8091:8091
    container_name: gymservicecontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  enquiryservice:
    build: ./EnquiryService
    image: enquiry-service:1.0-local
    restart: always
    ports:
      - 8092:8092
    container_name: enquiryservicecontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - rabbitmq
      - mongo
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  ticketservice:
    build: ./TicketService
    image: ticket-service:1.0-local
    restart: always
    ports:
      - 8093:8093
    container_name: ticketservicecontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - rabbitmq
      - mongo
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  frontend:
    image: 123sabana/goldysgym-ui:1.0
    restart: always
    ports:
      - 4200:4200
    container_name: frontendcontainer
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - rabbitmq
      - mongo
      - zipkin
      - configservice
      - eurekaservice
      - apigateway
