version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    container_name: rabbitmq_container

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    container_name: zipkin_container


  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb

  mongo:
    image: mongo:latest
    container_name: mongo_container

  configservice:
    image: somsubhramkh/config-service:1.0-local
    restart: always
    container_name: configservice_container
    depends_on:
      - zipkin

  eurekaservice:
    image: somsubhramkh/eureka-service:1.0-local
    ports:
      - 8761:8761
    restart: always
    container_name: eurekaservice_container
    depends_on:
      - zipkin
      - configservice

  apigateway:
    image: somsubhramkh/api-gateway:1.0-local
    ports:
      - 9000:9000
    restart: always
    container_name: apigateway_container
    depends_on:
      - zipkin
      - configservice
      - eurekaservice

  userservice:
    image: somsubhramkh/user-service:1.0-local
    ports:
      - 8090:8090
    restart: always
    container_name: userservice_container
    depends_on:
      - mysql
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  gymservice:
    image: somsubhramkh/gym-service:1.0-local
    ports:
      - 8091:8091
    restart: always
    container_name: gymservice_container
    depends_on:
      - mongo
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  enquiryservice:
    image: somsubhramkh/enquiry-service:1.0-local
    ports:
      - 8092:8092
    restart: always
    container_name: enquiryservice_container
    depends_on:
      - mongo
      - rabbitmq
      - zipkin
      - configservice
      - eurekaservice
      - apigateway


  ticketservice:
    image: somsubhramkh/ticket-service:1.0-local
    ports:
      - 8093:8093
    restart: always
    container_name: ticketservice_container
    depends_on:
      - mongo
      - rabbitmq
      - zipkin
      - configservice
      - eurekaservice
      - apigateway
