version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    container_name: rabbitmq_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    container_name: zipkin_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s


  mysql:
    image: mysql:latest
    container_name: mysql_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb


  mongo:
    image: mongo:latest
    container_name: mongo_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s

  configservice:
    build: ./ConfigService
    image: config-service:1.0-local
    restart: always
    container_name: configservice_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - zipkin

  eurekaservice:
    build: ./EurekaService
    image: eureka-service:1.0-local
    ports:
      - 8761:8761
    restart: always
    container_name: eurekaservice_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - zipkin
      - configservice

  apigateway:
    build: ./ApiGatewayService
    image: api-gateway:1.0-local
    ports:
      - 9000:9000
    restart: always
    container_name: apigateway_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - zipkin
      - configservice
      - eurekaservice

  userservice:
    build: ./UserService
    image: user-service:1.0-local
    ports:
      - 8090:8090
    restart: always
    container_name: userservice_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - mysql
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  gymservice:
    build: ./GymService
    image: gym-service:1.0-local
    ports:
      - 8091:8091
    restart: always
    container_name: gymservice_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

  enquiryservice:
    build: ./EnquiryService
    image: enquiry-service:1.0-local
    ports:
      - 8092:8092
    restart: always
    container_name: enquiryservice_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
      - rabbitmq
      - zipkin
      - configservice
      - eurekaservice
      - apigateway


  ticketservice:
    build: ./TicketService
    image: ticket-service:1.0-local
    ports:
      - 8093:8093
    restart: always
    container_name: ticketservice_container
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
      - rabbitmq
      - zipkin
      - configservice
      - eurekaservice
      - apigateway

