server:
  port: 9000
spring:
  zipkin:
    base-url: http://zipkin:9411/
zuul:
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    userservice:
      serviceId: user-service
    gymservice:
      serviceId: gym-service
    enquiryservice:
      serviceId: enquiry-service
    ticketservice:
      serviceId: ticket-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka