# service should start with port number 8092. mongodb database name and
# port number should be accepted using environment variable
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"

server:
  port: 8092
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 100
  data:
    mongodb:
      uri: ${MONGO_URI}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka