server:
  port: 8093
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 100
  data:
    mongodb:
      uri: ${MONGO_URI}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka