# server should start with port number 8090. MySQL database config parameters
# should be accepted using environment variable
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"


server:
  port: 8090
spring:
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 100
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka

